
version: '3'

services:

  docker-registry:
    image: registry:2
    container_name: docker-registry
    ports:
      - 5000:5000
    restart: always
    volumes:
      - ./volumes/registry:/var/lib/registry
    environment:
      REGISTRY_STORAGE_DELETE_ENABLED: 'true'

  docker-registry-ui:
    image: parabuzzle/craneoperator
    container_name: docker-registry-ui
    ports:
      - 5001:80
    restart: always
    environment:
      REGISTRY_HOST: docker-registry
      REGISTRY_PORT: 5000
      REGISTRY_PROTOCOL: http
      SSL_VERIFY: 'false'
      ALLOW_REGISTRY_LOGIN: 'true'
      REGISTRY_ALLOW_DELETE: 'true'

  #  docker-registry-ui:
  #    image: konradkleine/docker-registry-frontend:v2
  #    container_name: docker-registry-ui
  #    ports:
  #      - 8083:80
  #    restart: always
  #    environment:
  #      ENV_DOCKER_REGISTRY_HOST: docker-registry
  #      ENV_DOCKER_REGISTRY_PORT: 5000
